#ifndef __TOP_MISC_H__
#define __TOP_MISC_H__

#define TOP_CONF_INFO		0x004
#define TOP_SYS_CTRL_REG	0x008
#define TOP_USB_PHY_CTRL_REG	0x048
#define TOP_SDMA_DMA_CH_REMAP0	0x154
#define TOP_SDMA_DMA_CH_REMAP1	0x158
#define TOP_TOP_TIMER_CLK_SEL	0x1A0
#define TOP_TOP_WDT_CTRL	0x1A8
#define TOP_DDR_AXI_URGENT_OW	0x1B8
#define TOP_DDR_AXI_URGENT	0x1BC
#define TOP_DDR_AXI_QOS_0	0x1D8
#define TOP_DDR_AXI_QOS_1	0x1DC
#define TOP_SD_PWRSW_CTRL	0x1F4
#define TOP_SD_PWRSW_TIME	0x1F8
#define TOP_DDR_AXI_QOS_OW	0x23C
#define TOP_SD_CTRL_OPT		0x294
#define TOP_SDMA_DMA_INT_MUX	0x298

#endif // __TOP_MISC_H__